---
kind: pipeline
type: kubernetes
name: build
steps:
- name: binary
  image: docker.io/golang:1.19
  commands:
  - go build -v -a -tags netgo -o release/linux/amd64/kaniko-docker ./cmd/kaniko-docker
  environment:
    GOOS: "linux"
    GOARCH: "amd64"
    CGO_ENABLED: "0"
    GO111MODULE: "on"
- name: image
  pull: always
  image: images.home.mtaylor.io/drone-kaniko:latest
  settings:
    repo: images.home.mtaylor.io/drone-kaniko
    auto_tag: true
    enable_cache: true
    registry: images.home.mtaylor.io
trigger:
  event:
  - custom
  - push
  - tag
---
kind: pipeline
type: kubernetes
name: promote
steps:
- name: release
  image: images.home.mtaylor.io/deployer:0.1.0
  commands:
  - set -u
  - git fetch origin 'refs/tags/*:refs/tags/*'
  - git fetch origin $${DRONE_BRANCH}
  - export tag=$(get-release-tag)
  - git tag $${tag}
  - git push origin $${tag}
trigger:
  event:
  - promote
  target:
  - production
